#!/usr/bin/env bash


spam () {
  echo ""
  echo "Benchmark:"
  echo "PARTITION_COUNT = $PARTITION_COUNT"
  echo "TOTAL_MEMORY_THRESHOLD = $TOTAL_MEMORY_THRESHOLD"
  echo "CONSUMERS_PER_PARTITION = $CONSUMERS_PER_PARTITION"
  echo "DEQUEUE_LIMIT" = $DEQUEUE_LIMIT
  echo "--------------------------------------------------------"
  mix run --no-halt &
  pid=$!
  echo "Preparing to start..."
  sleep 5
  wrk -t8 -c64 -d30s -s spam.wrk "http://localhost:8099"
  echo "Shutting down"
  sleep 10
  kill -9 $pid
}

PARTITION_COUNT=8 TOTAL_MEMORY_THRESHOLD=1000000 CONSUMERS_PER_PARTITION=1 DEQUEUE_LIMIT=1 spam
PARTITION_COUNT=8 TOTAL_MEMORY_THRESHOLD=1000000 CONSUMERS_PER_PARTITION=4 DEQUEUE_LIMIT=1 spam
PARTITION_COUNT=8 TOTAL_MEMORY_THRESHOLD=1000000 CONSUMERS_PER_PARTITION=1 DEQUEUE_LIMIT=4 spam
PARTITION_COUNT=8 TOTAL_MEMORY_THRESHOLD=1000000 CONSUMERS_PER_PARTITION=4 DEQUEUE_LIMIT=8 spam

PARTITION_COUNT=8 TOTAL_MEMORY_THRESHOLD=1000000 CONSUMERS_PER_PARTITION=8 DEQUEUE_LIMIT=1 spam
PARTITION_COUNT=8 TOTAL_MEMORY_THRESHOLD=1000000 CONSUMERS_PER_PARTITION=8 DEQUEUE_LIMIT=8 spam
PARTITION_COUNT=8 TOTAL_MEMORY_THRESHOLD=1000000 CONSUMERS_PER_PARTITION=8 DEQUEUE_LIMIT=16 spam
PARTITION_COUNT=8 TOTAL_MEMORY_THRESHOLD=1000000 CONSUMERS_PER_PARTITION=16 DEQUEUE_LIMIT=16 spam
